language: python
python:
  - "2.6"
  - "2.7"
install:
  - "sudo apt-get install cython libdata-visitor-perl libjson-perl libmodule-load-perl libevent-dev"
  - "cd javascript && npm install && cd -"
script:
  - "python setup.py test"
