language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "sudo apt-get install cython libdata-visitor-perl libjson-perl libmodule-load-perl libevent-dev"
script:
  - "python setup.py test"
